// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQx7jeT_m1X5lRF1Y899hjIKFzgfJMeFI',
    appId: '1:532740482554:web:31fffdfb2b1529b80cf043',
    messagingSenderId: '532740482554',
    projectId: 'bookstore-5c8f6',
    authDomain: 'bookstore-5c8f6.firebaseapp.com',
    storageBucket: 'bookstore-5c8f6.firebasestorage.app',
    measurementId: 'G-G9YS1EKHKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnnoajz25zZ2Jp20-d1GPMmElKgTYYn8w',
    appId: '1:532740482554:android:313af0f7afb292310cf043',
    messagingSenderId: '532740482554',
    projectId: 'bookstore-5c8f6',
    storageBucket: 'bookstore-5c8f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3-yelrEef_wMs0c_rT__2dCSv2A1-tg',
    appId: '1:532740482554:ios:ce002f1ab3fecb6b0cf043',
    messagingSenderId: '532740482554',
    projectId: 'bookstore-5c8f6',
    storageBucket: 'bookstore-5c8f6.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3-yelrEef_wMs0c_rT__2dCSv2A1-tg',
    appId: '1:532740482554:ios:ce002f1ab3fecb6b0cf043',
    messagingSenderId: '532740482554',
    projectId: 'bookstore-5c8f6',
    storageBucket: 'bookstore-5c8f6.firebasestorage.app',
    iosBundleId: 'com.example.bookstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQx7jeT_m1X5lRF1Y899hjIKFzgfJMeFI',
    appId: '1:532740482554:web:4ea6421b61078f360cf043',
    messagingSenderId: '532740482554',
    projectId: 'bookstore-5c8f6',
    authDomain: 'bookstore-5c8f6.firebaseapp.com',
    storageBucket: 'bookstore-5c8f6.firebasestorage.app',
    measurementId: 'G-8LMYVJ7PZD',
  );
}
